export type {
	ActivityRecord,
	ActivitySummary,
	LapMarker,
	ParsedActivity,
	Interval,
	SelectionStats,
	StoredRecord,
	ActivityListItem,
	StoredActivity,
	CreateActivityBody,
	IntervalConfig,
	UpdateIntervalsBody,
	WaxedChainReminderSettings,
	UpdateWaxedChainReminderSettingsBody,
	CoachModelSettings,
	UpdateCoachModelSettingsBody,
	UpdateFavoriteModelsBody,
	TrainerMessage,
	TrainerThread,
	TrainerChatHistory,
	SaveTrainerHistoryBody,
	OpenwearablesSettings,
	UpdateOpenwearablesSettingsBody,
	HealthAutoExportSettings,
	HealthSource,
	CompareSettings,
	UpdateCompareSettingsBody,
	HealthData,
	HealthContext,
	HealthMetric,
	HealthMetricStatus,
	ActivityStats,
	SleepStages,
	RecentNight,
	HeatmapPoint,
	HeatmapResponse,
	StravaClub,
	StravaClubEvent,
	HealthHistoryEntry,
	ToolParameter,
	ToolDefinition,
	ToolCall,
	ToolResult,
	UIToolCall,
	UIToolCallStatus,
	ToolStreamChunk,
	TrainerStreamChunk,
	ChartHighlight,
	AthleteProfile,
	UpdateAthleteProfileBody,
	UpdateZoneOverridesBody,
	ProfileChangeEntry,
	ProfileChangeSource,
} from "./types.js";

export {
	APPROX_CHARS_PER_TOKEN,
	estimateContextTokens,
	PROFILE_CHANGE_SOURCE_LABELS,
} from "./types.js";

export {
	AVAILABLE_MODELS,
	getCoachModelDisplayName,
	getModelProvider,
} from "./coachModels.js";
export type { AvailableModelId, ModelEntry, Provider } from "./coachModels.js";

export {
	buildPowerBySecond,
	buildCadenceBySecond,
	buildMetricBySecondFromTimeSeries,
	mapStoredRecords,
	computeNormalizedPower,
	normalizedPowerFromSeconds,
	computeNormalizedCadence,
	normalizedCadenceFromSeconds,
	peakPowerFromSeconds,
	peakPowerFromTimeSeries,
} from "./power.js";

export type {
	ZoneBand,
	ZoneRange,
	ZoneOverride,
	ZonesResponse,
} from "./zones.js";
export {
	POWER_ZONE_BANDS,
	HR_ZONE_BANDS,
	resolveZones,
	applyZoneOverrides,
	isZoneOverride,
	isZoneOverrideArray,
	normalizeZoneOverride,
	normalizeZoneOverrides,
	formatZoneRange,
} from "./zones.js";

export { parseFit } from "./parseFit.js";
