export type {
	ActivityRecord,
	ActivitySummary,
	LapMarker,
	ParsedActivity,
	Interval,
	SelectionStats,
	StoredRecord,
	ActivityListItem,
	StoredActivity,
	CreateActivityBody,
	IntervalConfig,
	UpdateIntervalsBody,
	WaxedChainReminderSettings,
	UpdateWaxedChainReminderSettingsBody,
	CoachModelSettings,
	UpdateCoachModelSettingsBody,
	UpdateFavoriteModelsBody,
	TrainerMessage,
	TrainerThread,
	TrainerChatHistory,
	SaveTrainerHistoryBody,
	OpenwearablesSettings,
	UpdateOpenwearablesSettingsBody,
	HealthAutoExportSettings,
	HealthSource,
	CompareSettings,
	UpdateCompareSettingsBody,
	HealthData,
	HealthContext,
	HealthMetric,
	HealthMetricStatus,
	ActivityStats,
	SleepStages,
	RecentNight,
	HeatmapPoint,
	HeatmapResponse,
	StravaClub,
	StravaClubEvent,
	HealthHistoryEntry,
} from "./types.js";

export {
	AVAILABLE_MODELS,
	getCoachModelDisplayName,
	getModelProvider,
} from "./coachModels.js";
export type { AvailableModelId, ModelEntry, Provider } from "./coachModels.js";

export {
	buildPowerBySecond,
	buildCadenceBySecond,
	computeNormalizedPower,
	normalizedPowerFromSeconds,
	computeNormalizedCadence,
	normalizedCadenceFromSeconds,
	peakPowerFromSeconds,
} from "./power.js";
